baseURL = "localhost"
title = "Xavier Valcarce"
languageCode = "en-us"
theme = "nord-hello-friend-ng"
paginate = 10

[params]
  dateform        = "Feb 6, 2020"
  dateformShort   = "Feb 6"
  dateformNum     = "2020-01-01"
  dateformNumTime = "2020-01-01 04:20"

  # Subtitle for home
  homeSubtitle = "PhD Student in Quantum Information Theory"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Code highlighting
  # pygmentsCodeFences = true
  # pygmentsUseClasses = true

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/@plut0n_"

  [[params.social]]
    name = "email"
    url  = "mailto:xvalcarce@protonmail.com"

  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/plut0n"

  [[params.social]]
	name = "scholar"
	url  = "https://scholar.google.ch/citations?user=OULhh8IAAAAJ"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Xavier Valcarce"
    subtitle = "Physicist"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "valcarce.fr $ "
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "resume/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
